# server port and request prefix config
server:
  port: 8081
  servlet:
    context-path: /


# durian datasource
durian:
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.52:3306/durian?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: app
    password: AI7QKmenecZTovilwgPdds6x2qutcjBFzkmoBDkiiUwwili2s7YEjC+sOvI7BjQ7doQHRjzm03Fu0k6x9c+18g==
  config:
    decrypt: true
    druid:
      publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKFMEqQEFxSq4qmr2prehqVU88+s4qp7kpgn/Yi80rV6DdJCJsxXwXkwJg2dy0jrsndXZq125FcfWJIWrGezXtECAwEAAQ==


# bigdata datasource
bigdata:
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.52:3306/bigdata?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: app
    password: AI7QKmenecZTovilwgPdds6x2qutcjBFzkmoBDkiiUwwili2s7YEjC+sOvI7BjQ7doQHRjzm03Fu0k6x9c+18g==
  config:
    decrypt: true
    druid:
      publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKFMEqQEFxSq4qmr2prehqVU88+s4qp7kpgn/Yi80rV6DdJCJsxXwXkwJg2dy0jrsndXZq125FcfWJIWrGezXtECAwEAAQ==


# redis config
redis:
  cluster:
    servers: 192.168.1.53:5067
    commandTimeout: 5000